### ISSUE TITLE
I think I need to run it twice to work

### ISSUE THREAD

**Issue by bbigras** [Infinisil/nixus#17] opened 2020-07-14 17:09 UTC
If I'm on my desktop and I build and "push" a new config to my laptop. If I only do it once I don't see the new generation in the systemd boot menu but I do if I do it twice.

Also, not sure if I should open another issue for this, but often the systemd boot menu doesn't propose the latest generation when I boot.

**Comment by Infinisil** [comment] 2020-07-14 18:40
Ah! This has been reported before (on IRC) by @lovesegfault. I noticed indeed that there was a problem with the switching, but couldn't reproduce it, so I waited for the time being until I actually understand the problem. I get it now though, I just failed to reproduce it because I didn't notice the problem.

Thanks for the report, this should be fixed with 0a5c95553dc0f19f5daa9cebc016f4e3235992d7 now :)

**Closed by Infinisil** 2020-07-14 18:40 UTC

**Comment by bbigras** [comment] 2020-07-14 18:59
Nice thanks. I was kinda afraid of opening this issue in case I was the one doing something wrong.

Thanks again. :heart:
